### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by flatcap** [brankas/git-buildnumber#5]
I've just given git-buildnumber a try.
It's a great concept, but the performance leaves a little to be desired:
```
$ git count
total 8888

$ time git buildnumber 
v20.4.11.0

real  15m1.018s
user  19m13.620s
sys    0m28.517s
```

Quarter of an hour :-)

**Comment by mvdan** [comment]
What repository did you run it on?

**Comment by mvdan** [comment]
Please also specify what branch (commit hash) you ran it on.

**Comment by kenshaw** [comment]
Considering that `git-buildnumber` relies on a third-party Git package, I'm not sure this can be sped up much. I just ran `git-buildnumber` on the largest repository I know of (chromium), and at least on my hardware, it only took roughly 3 minutes, while a `git rev-list HEAD --count` took 6 seconds:

```sh
$ time git-buildnumber 
v17.3.18.0

real	2m57.646s
user	5m6.844s
sys	0m17.625s
$ time git rev-list HEAD --count
664342

real	0m5.833s
user	0m5.712s
sys	0m0.120s
```

Likely, this would require significantly modifying the underlying Git package being used, to only scan the "headers" of commits.

@flatcap can you give us more information about how you're using `git-buildnumber`? Also, flattered that you even are considering to use it!

**Comment by flatcap** [comment]
> What repository did you run it on?

https://github.com/neomutt/neomutt (20 years, nearly 9000 commits)

> Please also specify what branch (commit hash) you ran it on.

I ran it on [1d811a736](https://github.com/neomutt/neomutt/commit/1d811a736c4e01307aeaa17526375b8a9f8924ef) which is a couple of commits behind the current master.

> I just ran git-buildnumber on the largest repository I know of (chromium),
> and at least on my hardware, it only took roughly 3 minutes,
> while a git rev-list HEAD --count took 6 seconds:

My laptop's not cutting edge, but it's still fairly fast.

Odd.  Most git commands on the repo run (near) instantaneously.
Count: `git rev-list HEAD --count`  0.1s
First commit: `git log --oneline | tail -1` 0.25s
Today's commits: `git log --oneline --since="00:00"` 0.01s

> I'm not sure this can be sped up much

The NeoMutt repo was originally converted from an SVN repo (which was previous CVS).
There's quite possibly some degenerate characteristic at play.

Unfortunately, I don't speak 'go', or I'd investigate further.

> flattered that you even are considering to use it!

Well... I saw a shiny new git thing, how could I resist :-)

**Comment by kenshaw** [comment]
@flatcap -- no idea why it took 15 minutes on your hardware. Do you have a failing disk or some such? It takes roughly 1.5 seconds to run on the `neomutt` source with my equipment, which is a 2010-era i7, 16 gigs of ram, and a 2010-era SSD:

```sh
$ time git-buildnumber 
v20.4.12.17

real	0m1.768s
user	0m2.091s
sys	0m0.295s
$ time git rev-list HEAD --count
8912

real	0m0.057s
user	0m0.056s
sys	0m0.001s
```

Also, it might be worth pointing out that `git-buildnumber` is primarily designed / useful for build pipelines. If you intend to use it that way, you can cut down the time needed for its run by seeding the year value:
```sh
$ git-buildnumber --help
Usage of git-buildnumber:
  -inverse string
    	string to inverse
  -prefix string
    	prefix (default "v")
  -rev string
    	git revision (default "HEAD")
  -sep string
    	field separator (default ".")
  -short
    	trim last "<sep>0" from version
  -year string
    	start year offset
$ time git-buildnumber
v20.4.12.17

real	0m1.864s
user	0m2.197s
sys	0m0.320s
$ time git-buildnumber -year=1998
v20.4.12.17

real	0m0.919s
user	0m1.062s
sys	0m0.187s
```

**Comment by kenshaw** [comment]
Also -- I will make a point into looking into performance on this, but it's not a high priority for now, as I'm fairly certain this performance will be related to `go-git` and likely not fixable without a massive rewrite of `go-git`.

**Comment by flatcap** [comment]
I tried it on another machine and it was fast (1.5s).
Then it struck me what was different about my work account -- `git clone --reference`

I have one master repo and the others are cloned from it.
The clones have a `.git/objects/info/alternates` file to point to the parent.

If I run `git repack -ad` (pulling the resources to the clone), `buildnumber` runs quickly.

> If you intend to use it ...

It's a great alternative to our date-based release numbers, but...
it would mean adding a build dependency on `go`.

**Comment by mvdan** [comment]
> it would mean adding a build dependency on go

How so? This is a static binary that doesn't even depend on git, so you can bundle it in a Docker image, download it at run-time, etc.

**Comment by flatcap** [comment]
Oh!  Sorry.  Forgive my ignorance.

**Comment by mvdan** [comment]
The only possible confusion at the moment is that we don't publish a binary, mainly because we don't tag releases and expect to have many users. But it should be trivial to build a static binary for Linux if you have Go installed.
